---
plugins/chiliproject_activity_module:
  repository: "git@github.com:finnlabs/chiliproject_activity_module.git"
  branch: master
plugins/chiliproject_help_link:
  repository: "git@github.com:finnlabs/chiliproject_help_link.git"
  branch: master
plugins/numbered_headings:
  repository: "git@github.com:finnlabs/numbered_headings.git"
  branch: master
plugins/redmine_checkout:
  repository: "git@github.com:finnlabs/redmine_checkout.git"
  branch: master
plugins/redmine_customize_modules:
  repository: "git@github.com:finnlabs/redmine_customize_modules.git"
  branch: master
plugins/redmine_favicon:
  repository: "https://github.com/finnlabs/redmine_favicon"
  branch: master
plugins/memcached_passenger:
  repository: "git@github.com:finnlabs/memcached_passenger.git"
  branch: master
